// Generated by ts-to-zod
import { z } from "zod";
import { Json } from "./types";

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const badgesRowSchema = z.object({
  completed_projects: z.number().nullable(),
  id: z.number(),
  name: z.string(),
});

export const badgesInsertSchema = z.object({
  completed_projects: z.number().optional().nullable(),
  id: z.number().optional(),
  name: z.string(),
});

export const badgesUpdateSchema = z.object({
  completed_projects: z.number().optional().nullable(),
  id: z.number().optional(),
  name: z.string().optional(),
});

export const chaptersRowSchema = z.object({
  completed_at: z.string().nullable(),
  created_at: z.string(),
  id: z.string(),
  name: z.string(),
  order: z.number(),
  project_id: z.string(),
  state: z.number(),
  updated_at: z.string(),
});

export const chaptersInsertSchema = z.object({
  completed_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  name: z.string(),
  order: z.number(),
  project_id: z.string(),
  state: z.number(),
  updated_at: z.string().optional(),
});

export const chaptersUpdateSchema = z.object({
  completed_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  name: z.string().optional(),
  order: z.number().optional(),
  project_id: z.string().optional(),
  state: z.number().optional(),
  updated_at: z.string().optional(),
});

export const checkpointsRowSchema = z.object({
  chapter_id: z.string(),
  completed_at: z.string().nullable(),
  created_at: z.string(),
  id: z.string(),
  name: z.string(),
  order: z.number(),
  state: z.number(),
  updated_at: z.string(),
});

export const checkpointsInsertSchema = z.object({
  chapter_id: z.string(),
  completed_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  name: z.string(),
  order: z.number(),
  state: z.number(),
  updated_at: z.string().optional(),
});

export const checkpointsUpdateSchema = z.object({
  chapter_id: z.string().optional(),
  completed_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  name: z.string().optional(),
  order: z.number().optional(),
  state: z.number().optional(),
  updated_at: z.string().optional(),
});

export const contributorsRowSchema = z.object({
  created_at: z.string(),
  profile_id: z.string(),
  project_id: z.string(),
  role_id: z.number(),
  updated_at: z.string(),
});

export const contributorsInsertSchema = z.object({
  created_at: z.string().optional(),
  profile_id: z.string(),
  project_id: z.string(),
  role_id: z.number(),
  updated_at: z.string().optional(),
});

export const contributorsUpdateSchema = z.object({
  created_at: z.string().optional(),
  profile_id: z.string().optional(),
  project_id: z.string().optional(),
  role_id: z.number().optional(),
  updated_at: z.string().optional(),
});

export const eventsRowSchema = z.object({
  created_at: z.string(),
  end_date: z.string(),
  id: z.number(),
  project_id: z.string(),
  start_date: z.string(),
  title: z.string(),
  updated_at: z.string(),
});

export const eventsInsertSchema = z.object({
  created_at: z.string().optional(),
  end_date: z.string(),
  id: z.number().optional(),
  project_id: z.string(),
  start_date: z.string(),
  title: z.string(),
  updated_at: z.string().optional(),
});

export const eventsUpdateSchema = z.object({
  created_at: z.string().optional(),
  end_date: z.string().optional(),
  id: z.number().optional(),
  project_id: z.string().optional(),
  start_date: z.string().optional(),
  title: z.string().optional(),
  updated_at: z.string().optional(),
});

export const levelsRowSchema = z.object({
  id: z.number(),
  points: z.number(),
  value: z.number(),
});

export const levelsInsertSchema = z.object({
  id: z.number().optional(),
  points: z.number(),
  value: z.number(),
});

export const levelsUpdateSchema = z.object({
  id: z.number().optional(),
  points: z.number().optional(),
  value: z.number().optional(),
});

export const pointsRowSchema = z.object({
  action: z.string().nullable(),
  description: z.string().nullable(),
  id: z.number(),
  value: z.number(),
});

export const pointsInsertSchema = z.object({
  action: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  id: z.number().optional(),
  value: z.number(),
});

export const pointsUpdateSchema = z.object({
  action: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  id: z.number().optional(),
  value: z.number().optional(),
});

export const postsRowSchema = z.object({
  body: z.string().nullable(),
  created_at: z.string(),
  id: z.string(),
  profile_id: z.string(),
  title: z.string(),
  updated_at: z.string(),
});

export const postsInsertSchema = z.object({
  body: z.string().optional().nullable(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  profile_id: z.string(),
  title: z.string(),
  updated_at: z.string().optional(),
});

export const postsUpdateSchema = z.object({
  body: z.string().optional().nullable(),
  created_at: z.string().optional(),
  id: z.string().optional(),
  profile_id: z.string().optional(),
  title: z.string().optional(),
  updated_at: z.string().optional(),
});

export const postsUpvotesRowSchema = z.object({
  created_at: z.string(),
  post_id: z.string(),
  upvoted_by: z.string(),
});

export const postsUpvotesInsertSchema = z.object({
  created_at: z.string().optional(),
  post_id: z.string(),
  upvoted_by: z.string(),
});

export const postsUpvotesUpdateSchema = z.object({
  created_at: z.string().optional(),
  post_id: z.string().optional(),
  upvoted_by: z.string().optional(),
});

export const profilesRowSchema = z.object({
  avatar: z.string().nullable(),
  bio: z.string().nullable(),
  created_at: z.string(),
  discord: z.string().nullable(),
  dream: z.string().nullable(),
  email: z.string(),
  github: z.string().nullable(),
  id: z.string(),
  location: z.string().nullable(),
  muted: z.boolean().nullable(),
  name: z.string().nullable(),
  twitch: z.string().nullable(),
  twitter: z.string().nullable(),
  updated_at: z.string(),
  username: z.string(),
});

export const profilesInsertSchema = z.object({
  avatar: z.string().optional().nullable(),
  bio: z.string().optional().nullable(),
  created_at: z.string().optional(),
  discord: z.string().optional().nullable(),
  dream: z.string().optional().nullable(),
  email: z.string(),
  github: z.string().optional().nullable(),
  id: z.string(),
  location: z.string().optional().nullable(),
  muted: z.boolean().optional().nullable(),
  name: z.string().optional().nullable(),
  twitch: z.string().optional().nullable(),
  twitter: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  username: z.string(),
});

export const profilesUpdateSchema = z.object({
  avatar: z.string().optional().nullable(),
  bio: z.string().optional().nullable(),
  created_at: z.string().optional(),
  discord: z.string().optional().nullable(),
  dream: z.string().optional().nullable(),
  email: z.string().optional(),
  github: z.string().optional().nullable(),
  id: z.string().optional(),
  location: z.string().optional().nullable(),
  muted: z.boolean().optional().nullable(),
  name: z.string().optional().nullable(),
  twitch: z.string().optional().nullable(),
  twitter: z.string().optional().nullable(),
  updated_at: z.string().optional(),
  username: z.string().optional(),
});

export const profilesBadgesRowSchema = z.object({
  badge_id: z.number(),
  created_at: z.string(),
  profile_id: z.string(),
});

export const profilesBadgesInsertSchema = z.object({
  badge_id: z.number(),
  created_at: z.string().optional(),
  profile_id: z.string(),
});

export const profilesBadgesUpdateSchema = z.object({
  badge_id: z.number().optional(),
  created_at: z.string().optional(),
  profile_id: z.string().optional(),
});

export const profilesPointsRowSchema = z.object({
  created_at: z.string(),
  id: z.string(),
  point_id: z.number(),
  profile_id: z.string(),
});

export const profilesPointsInsertSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  point_id: z.number(),
  profile_id: z.string(),
});

export const profilesPointsUpdateSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  point_id: z.number().optional(),
  profile_id: z.string().optional(),
});

export const profilesUpvotesRowSchema = z.object({
  created_at: z.string(),
  profile_id: z.string(),
  upvoted_by: z.string(),
});

export const profilesUpvotesInsertSchema = z.object({
  created_at: z.string().optional(),
  profile_id: z.string(),
  upvoted_by: z.string(),
});

export const profilesUpvotesUpdateSchema = z.object({
  created_at: z.string().optional(),
  profile_id: z.string().optional(),
  upvoted_by: z.string().optional(),
});

export const projectsRowSchema = z.object({
  created_at: z.string(),
  description: z.string().nullable(),
  id: z.string(),
  logo: z.string().nullable(),
  profile_id: z.string(),
  state_id: z.number(),
  title: z.string(),
  updated_at: z.string(),
  url: z.string().nullable(),
});

export const projectsInsertSchema = z.object({
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  logo: z.string().optional().nullable(),
  profile_id: z.string(),
  state_id: z.number().optional(),
  title: z.string(),
  updated_at: z.string().optional(),
  url: z.string().optional().nullable(),
});

export const projectsUpdateSchema = z.object({
  created_at: z.string().optional(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  logo: z.string().optional().nullable(),
  profile_id: z.string().optional(),
  state_id: z.number().optional(),
  title: z.string().optional(),
  updated_at: z.string().optional(),
  url: z.string().optional().nullable(),
});

export const projectsUpvotesRowSchema = z.object({
  created_at: z.string(),
  project_id: z.string(),
  upvoted_by: z.string(),
});

export const projectsUpvotesInsertSchema = z.object({
  created_at: z.string().optional(),
  project_id: z.string(),
  upvoted_by: z.string(),
});

export const projectsUpvotesUpdateSchema = z.object({
  created_at: z.string().optional(),
  project_id: z.string().optional(),
  upvoted_by: z.string().optional(),
});

export const reportsRowSchema = z.object({
  created_at: z.string(),
  id: z.string(),
  profile_id: z.string(),
  reason: z.string().nullable(),
  reported_by: z.string(),
});

export const reportsInsertSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  profile_id: z.string(),
  reason: z.string().optional().nullable(),
  reported_by: z.string(),
});

export const reportsUpdateSchema = z.object({
  created_at: z.string().optional(),
  id: z.string().optional(),
  profile_id: z.string().optional(),
  reason: z.string().optional().nullable(),
  reported_by: z.string().optional(),
});

export const rolesRowSchema = z.object({
  id: z.number(),
  name: z.string().nullable(),
});

export const rolesInsertSchema = z.object({
  id: z.number().optional(),
  name: z.string().optional().nullable(),
});

export const rolesUpdateSchema = z.object({
  id: z.number().optional(),
  name: z.string().optional().nullable(),
});

export const statesRowSchema = z.object({
  id: z.number(),
  name: z.string(),
});

export const statesInsertSchema = z.object({
  id: z.number().optional(),
  name: z.string(),
});

export const statesUpdateSchema = z.object({
  id: z.number().optional(),
  name: z.string().optional(),
});

export const tasksRowSchema = z.object({
  assigned_by: z.string(),
  assigned_to: z.string(),
  checkpoint_id: z.string(),
  completed_at: z.string().nullable(),
  created_at: z.string(),
  description: z.string(),
  id: z.string(),
  state: z.number(),
  title: z.string(),
  updated_at: z.string(),
});

export const tasksInsertSchema = z.object({
  assigned_by: z.string(),
  assigned_to: z.string(),
  checkpoint_id: z.string(),
  completed_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  description: z.string(),
  id: z.string().optional(),
  state: z.number(),
  title: z.string(),
  updated_at: z.string().optional(),
});

export const tasksUpdateSchema = z.object({
  assigned_by: z.string().optional(),
  assigned_to: z.string().optional(),
  checkpoint_id: z.string().optional(),
  completed_at: z.string().optional().nullable(),
  created_at: z.string().optional(),
  description: z.string().optional(),
  id: z.string().optional(),
  state: z.number().optional(),
  title: z.string().optional(),
  updated_at: z.string().optional(),
});
